### ISSUE TITLE
Generate report against generic-WSGI histomicsUI

### ISSUE THREAD

**Issue by zachmullen** [DigitalSlideArchive/histomics_load_testing#2]
The current docker setup uses `girder serve`; we should have a documented way to run using alternative servers using [this branch](https://github.com/DigitalSlideArchive/HistomicsUI/tree/honor-the-wsgi).

**Comment by annehaley** [comment]
A first pass at the report has been shared via Google Docs : https://docs.google.com/spreadsheets/d/1pNGQlLpvv045YA6oSHyTZvtEKQeUxMKOXRXrq6AuJNI/edit#gid=0 (access to Kitware members only)

The Dockerfile now has several options for running alternative server configurations with that branch (since [2b181e2](https://github.com/DigitalSlideArchive/histomics_load_testing/commit/2b181e297fd364fc3c7542ba34f56fef767c51c8))
